const crypto = require('crypto');
const User = require('../models/User'); const Hostel = require('../models/Hostel'); const Invite = require('../models/AdminInvite');
const env = require('../config/env'); const ApiError = require('../utils/ApiError'); const asyncHandler = require('../utils/asyncHandler'); const { sendSuccess } = require('../utils/response');
const hash = token => crypto.createHash('sha256').update(token).digest('hex');
async function checkHostels(ids) { if (await Hostel.countDocuments({ _id: { $in: ids }, isActive: true }) !== ids.length) throw new ApiError(400, 'One or more selected hostels are unavailable.', 'HOSTEL_UNAVAILABLE'); }
const list = asyncHandler(async (_req, res) => { const [admins, invites] = await Promise.all([User.find({ role: 'admin' }).populate('managedHostels', 'name campus isActive').sort({ createdAt: -1 }), Invite.find({ acceptedAt: null, revokedAt: null, expiresAt: { $gt: new Date() } }).populate('managedHostels', 'name').sort({ createdAt: -1 })]); return sendSuccess(res, { message: 'Administrators retrieved.', data: { admins, invites } }); });
const createInvite = asyncHandler(async (req, res) => {
  const input = req.validated.body;
  if (await User.exists({ email: input.email })) throw new ApiError(409, 'An account already uses this email.', 'EMAIL_IN_USE');
  await checkHostels(input.managedHostels);
  await Invite.updateMany({ email: input.email, acceptedAt: null, revokedAt: null }, { revokedAt: new Date() });
  const token = crypto.randomBytes(32).toString('hex');
  const invite = await Invite.create({ ...input, tokenHash: hash(token), expiresAt: new Date(Date.now() + 172800000), invitedBy: req.user._id });
  const client = env.CLIENT_URL.split(',')[0].trim().replace(/\/$/, '');
  const inviteUrl = `${client}/accept-admin-invite?token=${token}`;
  return sendSuccess(res, { statusCode: 201, message: 'Administrator invitation created. Copy the link to send it.', data: { invite: { id: invite.id, email: invite.email, expiresAt: invite.expiresAt }, inviteUrl } });
});
const getInvite = asyncHandler(async (req, res) => { const invite = await Invite.findOne({ tokenHash: hash(req.validated.params.token), acceptedAt: null, revokedAt: null, expiresAt: { $gt: new Date() } }).populate('managedHostels', 'name campus'); if (!invite) throw new ApiError(404, 'This invitation is invalid or has expired.', 'INVITE_INVALID'); return sendSuccess(res, { message: 'Invitation retrieved.', data: { invite: { firstName: invite.firstName, surname: invite.surname, email: invite.email, managedHostels: invite.managedHostels, expiresAt: invite.expiresAt } } }); });
const accept = asyncHandler(async (req, res) => { const invite = await Invite.findOne({ tokenHash: hash(req.validated.body.token), acceptedAt: null, revokedAt: null, expiresAt: { $gt: new Date() } }); if (!invite) throw new ApiError(404, 'This invitation is invalid or has expired.', 'INVITE_INVALID'); if (await User.exists({ email: invite.email })) throw new ApiError(409, 'An account already uses this email.', 'EMAIL_IN_USE'); const user = await User.create({ firstName: invite.firstName, surname: invite.surname, email: invite.email, password: req.validated.body.password, role: 'admin', managedHostels: invite.managedHostels }); invite.acceptedAt = new Date(); await invite.save(); return sendSuccess(res, { statusCode: 201, message: 'Administrator account created. You can now sign in.', data: { user } }); });
const scope = asyncHandler(async (req, res) => { await checkHostels(req.validated.body.managedHostels); const admin = await User.findOneAndUpdate({ _id: req.validated.params.id, role: 'admin' }, { managedHostels: req.validated.body.managedHostels }, { new: true, runValidators: true }).populate('managedHostels', 'name campus'); if (!admin) throw new ApiError(404, 'Administrator not found.', 'ADMIN_NOT_FOUND'); return sendSuccess(res, { message: 'Administrator hostel assignment updated.', data: { admin } }); });
const status = asyncHandler(async (req, res) => { const admin = await User.findOneAndUpdate({ _id: req.validated.params.id, role: 'admin' }, { isActive: req.validated.body.isActive }, { new: true }).populate('managedHostels', 'name campus'); if (!admin) throw new ApiError(404, 'Administrator not found.', 'ADMIN_NOT_FOUND'); return sendSuccess(res, { message: req.validated.body.isActive ? 'Administrator access restored.' : 'Administrator access revoked.', data: { admin } }); });
const revokeInvite = asyncHandler(async (req, res) => { const invite = await Invite.findOneAndUpdate({ _id: req.validated.params.id, acceptedAt: null, revokedAt: null }, { revokedAt: new Date() }); if (!invite) throw new ApiError(404, 'Pending invitation not found.', 'INVITE_NOT_FOUND'); return sendSuccess(res, { message: 'Administrator invitation revoked.' }); });
module.exports = { list, createInvite, getInvite, accept, scope, status, revokeInvite };
